## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Abdulrahman Yusuf
#### Email: audura2013@gmail.com
#### Title: Week 1 Solution

In [2]:
import torch
import random

In [3]:
#  Q2: Solution
# Creating 7 by 7 random tensor
random_7x7 = torch.rand(size=(7,7))
random_7x7

tensor([[0.3450, 0.8720, 0.9598, 0.2645, 0.3541, 0.4297, 0.6647],
        [0.0057, 0.0112, 0.5115, 0.9058, 0.9094, 0.7625, 0.6441],
        [0.8778, 0.5759, 0.3240, 0.9175, 0.4520, 0.3294, 0.2131],
        [0.7771, 0.2319, 0.9948, 0.8812, 0.8307, 0.4557, 0.7334],
        [0.7917, 0.3892, 0.0600, 0.3200, 0.1702, 0.0868, 0.7133],
        [0.5057, 0.2033, 0.6818, 0.5775, 0.4035, 0.3287, 0.0521],
        [0.8662, 0.3234, 0.0031, 0.6716, 0.9963, 0.1485, 0.6250]])

In [4]:
#Q3: Solution
#creating 1 by 7 tensor
random_1x7 = torch.rand(size=(1,7))

#Multifly 7 by 7 tensor of Q2 with tensor 1 by 7 tensor just created
matrix_mult = torch.mm(random_7x7, random_1x7.T)
matrix_mult

tensor([[2.0961],
        [1.3953],
        [1.9189],
        [2.1739],
        [1.7993],
        [1.1009],
        [1.9590]])

In [5]:
#Q4: solution
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(0)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=7, # in_features = matches inner dimension of input
                         out_features=1) # out_features = describes outer value
y = random_7x7
matrix_mult = linear(y)
print(f"Input shape: {y.shape}\n")
print(f"Output:\n{matrix_mult}\n\nOutput shape: {matrix_mult.shape}")

Input shape: torch.Size([7, 7])

Output:
tensor([[ 0.0904],
        [-0.1691],
        [ 0.0240],
        [-0.2903],
        [ 0.2473],
        [-0.0591],
        [ 0.0404]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([7, 1])


In [13]:
torch.cuda?

In [7]:
#Q5: solution
# idea from the documemtaion
torch.cuda.is_available()

True

In [19]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [16]:
# Count number of devices
torch.cuda.device_count()

1

In [25]:
#Q6: Solution
import torch
import random

torch.manual_seed(1234)
tensor_A = torch.rand(size=(2,3))
tensor_B = torch.rand(size=(2,3))

# Tensors not on GPU
print(f"Tensor_A: \n{tensor_A, tensor_A.device}\n")
print(f"Tensor_B: \n{tensor_B, tensor_B.device}\n\n")

# Move tensors to GPU (if available)
tensor_A_on_gpu = tensor_A.to(device)
tensor_B_on_gpu = tensor_B.to(device)
print(f"tensor_A on GPU: \n{tensor_A_on_gpu}")
print(f"tensor_B on GPU: \n{tensor_B_on_gpu}")

Tensor_A: 
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), device(type='cpu'))

Tensor_B: 
(tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]), device(type='cpu'))


tensor_A on GPU: 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor_B on GPU: 
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [9]:
#Q7: Solution
#Matrix multiplication of two tensors of the same size
result_AXB = tensor_A @ tensor_B.reshape(3,2)

print(f"Output of tensor_A and tensor_B matrix mltiplcatin: \n{result_AXB} \n")

Output of tensor_A and tensor_B matrix mltiplcatin: 
tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]]) 



In [10]:
#Q8: Solution - Output the maximum and minimum values of the result of multiplicatom matrix

print(f"Maximum value of Q7 result: {result_AXB.max()}\n")
print(f"Minimum value of Q7 result: {result_AXB.min()}\n")

Maximum value of Q7 result: 0.6073753833770752

Minimum value of Q7 result: 0.2930890917778015



In [11]:
#Q9: Solution - Get the position of max and min of Q7 matrix multiplication
print(f"Get maximum value position  of Q7 result: {result_AXB.argmax()}\n")
print(f"Get minimum value position of Q7 result: {result_AXB.argmin()}\n")

Get maximum value position  of Q7 result: 2

Get minimum value position of Q7 result: 1



In [26]:
#Q10: solution

import torch
import random

#creation of tensor with (1,1,1,10) shape
random_tensor_Q10_A = torch.rand(size=(1, 1, 1, 10))

random_tensor_Q10_B = random_tensor_Q10_A.squeeze()

torch.manual_seed(7)
print(f"The first tensor created of Q10: \n{random_tensor_Q10_A}")
print(f"The shape of first created tensor of Q10: {random_tensor_Q10_A.shape}\n")
print(f"The second tensor created of Q10: \n{random_tensor_Q10_B}")
print(f"The shape of second created tensor of Q10: {random_tensor_Q10_B.shape}")


The first tensor created of Q10: 
tensor([[[[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313,
           0.6012, 0.3043]]]])
The shape of first created tensor of Q10: torch.Size([1, 1, 1, 10])

The second tensor created of Q10: 
tensor([0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757, 0.7842, 0.1525, 0.6662,
        0.3343])
The shape of second created tensor of Q10: torch.Size([10])
